[package]
name = "rust_control"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = { version = "7.2.1", default-features = false, features = ["dynamic-schema"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
