site_name: Grommet
site_description: High performance Python GraphQL server library
site_url: https://grommet.dev

repo_name: grommet
repo_url: https://github.com/thearchitector/grommet

theme:
  name: flatly
  custom_dir: docs/overrides

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Types:
    - Object Types: types/object-types.md
    - Input Types: types/input-types.md
    - Interfaces: types/interfaces.md
    - Scalars: types/scalars.md
    - Enums: types/enums.md
    - Unions: types/unions.md
  - Resolvers: resolvers.md
  - Subscriptions: subscriptions.md
  - Schema: schema.md
  - Runtime: runtime.md
  - API Reference: api-reference.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - css/custom.css
